# Generated by Django 5.2 on 2025-04-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("html_pdf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="htmlpdf",
            name="html",
            field=models.FileField(blank=True, null=True, upload_to="htmlpdf/html/"),
        ),
    ]
